Repository agiledev-students-fall2024/4-final-project-network, pull requests merged in 2024-12, with the labels that each got.

#96 Andy
  back-end/routes/main.js
  front-end/src/components/authContext.js
  front-end/src/screens/Explore.js
  front-end/src/screens/Home.js
Labels: Task

#98 Finished db integration
  back-end/routes/friends.js
  front-end/src/screens/FriendsAdd.js
  front-end/src/screens/FriendsBlocked.js
  front-end/src/screens/FriendsList.js
  front-end/src/screens/FriendsRequests.js
  front-end/src/screens/FriendsSearch.js
Labels: Task

#99 Andy
  front-end/src/screens/Createnewblogpost.js
  front-end/src/screens/Home.js
Labels: bug

#100 Multer middleware implementation for image upload
  back-end/app.js
  back-end/models/Post.js
  back-end/routes/posts.js
  back-end/uploads/1733191975244-pngimg.com - spongebob_PNG1.png
  back-end/uploads/1733192651992-pngimg.com - spongebob_PNG1.png
  back-end/uploads/1733193353173-sponge.png
  back-end/uploads/1733195726366-sponge2.png
  back-end/uploads/1733246420300-mePatrick.jpg
  back-end/uploads/1733246727267-helen1.png
  front-end/src/screens/Blogpostloggedin.js
  front-end/src/screens/Createnewblogpost.js
  front-end/src/screens/Explore.js
  front-end/src/screens/Home.js
  front-end/src/screens/Profile.js
  package.json
Labels: Task

#103 Code clean up plus added line break for display
  back-end/models/Post.js
  front-end/src/screens/Blogpostloggedin.js
  front-end/src/screens/Createnewblogpost.js
  front-end/src/screens/Home.js
Labels: bug

#109 Fixed author link and updated styling on Home/Explore
  back-end/routes/posts.js
  back-end/uploads/1733191975244-pngimg.com - spongebob_PNG1.png
  back-end/uploads/1733192651992-pngimg.com - spongebob_PNG1.png
  back-end/uploads/1733193353173-sponge.png
  back-end/uploads/1733195726366-sponge2.png
  back-end/uploads/1733246420300-mePatrick.jpg
  back-end/uploads/1733246727267-helen1.png
  back-end/uploads/1733628655029-sandy.jpg
  back-end/uploads/1733699764397-threePointBasketball.jpg
  back-end/uploads/1733699883000-loadMgmt.jpg
  back-end/uploads/1733699987036-modelSPlaid.jpg
  back-end/uploads/1733700038055-Porsche911RSR.jpg
  back-end/uploads/1733700140438-MargheritaPizza.webp
  back-end/uploads/1733700178209-wellingtonSteak.webp
  back-end/uploads/1733700262516-wizzOzz.jpg
  back-end/uploads/1733700299965-Inception.jpg
  back-end/uploads/1733700405188-TKAM.webp
  back-end/uploads/1733700443581-TNC.jpg
  front-end/src/screens/Blogpostloggedin.js
  front-end/src/screens/Explore.js
  front-end/src/screens/Home.js
  front-end/src/styles/Blogpostloggedin.css
  front-end/src/styles/Explore.css
  front-end/src/styles/Home.css
Labels: Task

#110 Added pop-up notifications and added friendships data
  back-end/seed.js
  front-end/src/screens/FriendsAdd.js
  front-end/src/screens/FriendsBlocked.js
  front-end/src/screens/FriendsList.js
  front-end/src/screens/FriendsRequests.js
  front-end/src/screens/FriendsSearch.js
  front-end/src/styles/FriendsAdd.css
  front-end/src/styles/FriendsBlocked.css
  front-end/src/styles/FriendsList.css
  front-end/src/styles/FriendsRequests.css
  front-end/src/styles/FriendsSearch.css
Labels: Task

#111 Code clean up
  front-end/src/screens/Blogpostloggedin.js
  front-end/src/styles/Blogpostloggedin.css
Labels: bug

#113 Fixed block button logic
  back-end/routes/friends.js
Labels: Task

#114 Small changes to profile and remove filler data
  back-end/fillerData/blocked.js
  back-end/fillerData/friendRequests.js
  back-end/fillerData/friendships.js
  back-end/fillerData/loggedIn.js
  back-end/fillerData/posts.js
  back-end/fillerData/users.js
  front-end/src/components/EditProfileForm.js
  front-end/src/fillerData/blocked.json
  front-end/src/fillerData/friendRequests.json
  front-end/src/fillerData/friendships.json
  front-end/src/fillerData/loggedIn.json
  front-end/src/fillerData/posts.json
  front-end/src/fillerData/users.json
  front-end/src/screens/Profile.js
Labels: Task

#115 Changed seed friendships
  back-end/seed.js
Labels: Task

#117 Put back edit post functionality
  back-end/routes/main.js
  back-end/routes/posts.js
Labels: bug

#121 Updated readme to include live link
  README.md
Labels: documentation
